<#
.SYNOPSIS
    Generates the documentation tag index and the per-folder .order files from YAML frontmatter.

.DESCRIPTION
    Re-run this after adding, renaming, or retagging any document.

    Two outputs:

    1. docs/tags.md - a plain markdown tag index. Deliberately plain rather than dependent on a
       renderer's native tag feature, so it works identically in the GitHub file browser, an Azure
       DevOps wiki, MkDocs, or a Confluence import.

    2. .order files - Azure DevOps "publish code as wiki" reads these to order pages within a folder.
       They are inert everywhere else, so carrying them costs nothing and keeps that option open.

.EXAMPLE
    .\scripts\Build-DocIndex.ps1
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
Push-Location $repoRoot

try {
    # docs/ is the wiki. Working material under working/ is deliberately not indexed here.
    $roots = @('docs')

    function Read-Frontmatter {
        param([string]$Path)

        $lines = Get-Content -LiteralPath $Path
        if ($lines.Count -lt 3 -or $lines[0] -ne '---') { return $null }

        $close = 1
        while ($close -lt $lines.Count -and $lines[$close] -ne '---') { $close++ }
        if ($close -ge $lines.Count) { return $null }

        $meta = @{}
        for ($i = 1; $i -lt $close; $i++) {
            if ($lines[$i] -notmatch '^([a-z_]+):\s*(.*)$') { continue }
            $key, $raw = $Matches[1], $Matches[2].Trim()

            if ($raw -match '^\[(.*)\]$') {
                $meta[$key] = @($Matches[1] -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ })
            }
            else {
                $meta[$key] = $raw.Trim('"', "'")
            }
        }
        $meta
    }

    $docs = @()
    foreach ($root in $roots) {
        Get-ChildItem $root -Recurse -Filter *.md -File |
            Where-Object { $_.FullName -notmatch '\\prototype\\' -and $_.Name -ne 'tags.md' } |
            ForEach-Object {
                $meta = Read-Frontmatter $_.FullName
                if (-not $meta) { return }
                $repoPath = $_.FullName.Replace("$repoRoot\", '').Replace('\', '/')

                # The index is written to docs/tags.md, so links must be relative to docs/.
                $linkPath = $repoPath.Substring(5)

                $docs += [pscustomobject]@{
                    Path  = $linkPath
                    Meta  = $meta
                }
            }
    }

    Write-Host "Indexed $($docs.Count) documents." -ForegroundColor Cyan

    # ---------- tag index ----------
    $sb = [Text.StringBuilder]::new()
    $null = $sb.AppendLine('---')
    $null = $sb.AppendLine('title: "Documentation tag index"')
    $null = $sb.AppendLine('domain: [docs]')
    $null = $sb.AppendLine('layer: []')
    $null = $sb.AppendLine('type: index')
    $null = $sb.AppendLine('status: current')
    $null = $sb.AppendLine('proof: documented')
    $null = $sb.AppendLine('audience: [engineer, operator, leadership]')
    $null = $sb.AppendLine('tags: [index, navigation, taxonomy]')
    $null = $sb.AppendLine("updated: $(Get-Date -Format 'yyyy-MM-dd')")
    $null = $sb.AppendLine('---')
    $null = $sb.AppendLine()
    $null = $sb.AppendLine('# Documentation tag index')
    $null = $sb.AppendLine()
    $null = $sb.AppendLine('Generated by `scripts/Build-DocIndex.ps1`. Do not edit by hand.')
    $null = $sb.AppendLine()
    $null = $sb.AppendLine("$($docs.Count) documents.")
    $null = $sb.AppendLine()

    function Add-Facet {
        param([string]$Heading, [string]$Key, [string]$Blurb)

        $null = $sb.AppendLine("## $Heading")
        $null = $sb.AppendLine()
        if ($Blurb) { $null = $sb.AppendLine($Blurb); $null = $sb.AppendLine() }

        $groups = @{}
        foreach ($d in $docs) {
            if (-not $d.Meta.ContainsKey($Key)) { continue }
            foreach ($v in @($d.Meta[$Key])) {
                if (-not $v) { continue }
                if (-not $groups.ContainsKey($v)) { $groups[$v] = @() }
                $groups[$v] += $d
            }
        }

        foreach ($name in ($groups.Keys | Sort-Object)) {
            $null = $sb.AppendLine("### $name")
            $null = $sb.AppendLine()
            foreach ($d in ($groups[$name] | Sort-Object { $_.Meta.title })) {
                $flag = ''
                if ($d.Meta.status -eq 'superseded') { $flag = ' **[superseded]**' }
                elseif ($d.Meta.status -eq 'draft')  { $flag = ' *(draft)*' }
                $null = $sb.AppendLine("- [$($d.Meta.title)]($($d.Path))$flag")
            }
            $null = $sb.AppendLine()
        }
    }

    Add-Facet 'By document type' 'type' 'What kind of document this is.'
    Add-Facet 'By depth' 'depth' 'How much hand-holding. A quickref is the commands you paste at a terminal with minimal prose. A guide is the full walkthrough with gotchas and expected output. Only procedural documents carry this.'
    Add-Facet 'By proof status' 'proof' 'Whether the content was demonstrated on real hardware, only documented, blocked by an external dependency, or never attempted. This is the facet that keeps the project honest.'
    Add-Facet 'By domain' 'domain' 'The technical area.'
    Add-Facet 'By layer' 'layer' 'Where in the stack the document applies.'
    Add-Facet 'By audience' 'audience' 'Who the document is written for.'

    # ---------- free tags ----------
    $null = $sb.AppendLine('## All topic tags')
    $null = $sb.AppendLine()
    $tagMap = @{}
    foreach ($d in $docs) {
        foreach ($t in @($d.Meta.tags)) {
            if (-not $t) { continue }
            if (-not $tagMap.ContainsKey($t)) { $tagMap[$t] = @() }
            $tagMap[$t] += $d
        }
    }
    foreach ($t in ($tagMap.Keys | Sort-Object)) {
        $links = ($tagMap[$t] | Sort-Object { $_.Meta.title } | ForEach-Object { "[$($_.Meta.title)]($($_.Path))" }) -join ', '
        $null = $sb.AppendLine("- **$t** -> $links")
    }
    $null = $sb.AppendLine()

    Set-Content -LiteralPath 'docs/tags.md' -Value $sb.ToString() -Encoding utf8
    Write-Host "  Wrote docs/tags.md ($($tagMap.Count) distinct tags)" -ForegroundColor Green

    # ---------- .order files ----------
    $orderCount = 0
    $folders = @('docs') + (Get-ChildItem 'docs' -Recurse -Directory | ForEach-Object { $_.FullName.Replace("$repoRoot\", '') })

    foreach ($folder in $folders) {
        if (-not (Test-Path -LiteralPath $folder)) { continue }
        $names = Get-ChildItem $folder -Filter *.md -File |
            ForEach-Object { $_.BaseName } |
            Sort-Object { if ($_ -in 'README', 'STATUS') { '0' } else { '1' + $_ } }

        if (-not $names) { continue }
        Set-Content -LiteralPath (Join-Path $folder '.order') -Value $names -Encoding ascii
        $orderCount++
    }
    Write-Host "  Wrote $orderCount .order files" -ForegroundColor Green
}
finally {
    Pop-Location
}
